### ISSUE TITLE
Browser (Firefox & Chrome) Hang On Avrodoc Generated HTML File

### ISSUE THREAD

**Issue by sherman94062** [ept/avrodoc#1]
Could be my problem, not sure, the install seemed to go okay.

The generated html file from my .avsc source is generated but then fails the render, the browser just seems to hang trying to load the file.

Thx,
Mike Sherman

**Comment by ept** [comment]
Hey Mike, can you give a bit more context?
- The .avsc file
- The browser version you're using
- Any exceptions appearing in your browser's JavaScript console

**Comment by sherman94062** [comment]
Thanks Martin.

The issue is indeed .avsc file specific.

Let me check on confidentiality and I'll send you an example file.

We may want to make our schema a little more compliant ... ;^)

Thx,
Mike

**Comment by inome** [comment]
Mike--

I am pretty confident that this is actually not a 'hang' per-say. The generated AVSC file is likely in a newer format than the code in the ept/avrodoc repository is currently built for and you are likely getting a javascript exception. See our pull request here that will resolve this issue: https://github.com/ept/avrodoc/pull/2

This version not only adds additional functionality to the output from the avrodoc generator but also resolves the issue of the 'hang' you are referring to. Basically, in later versions of the avrotools utility, the root object in the AVSC file is re-structured and the current avrodoc code doesn't handle that.

Thanks,
Micah
Software Engineer :: Inome, Inc

**Comment by sherman94062** [comment]
Excellent, Micah, thanks!

AvroDoc is very useful!!

-Mike

On Dec 19, 2012, at 7:49 AM, inome wrote:

> Make--
> 
> I am pretty confident that this is actually not a 'hang' per-say. The generated AVSC file is likely in a newer format than the code in the ept/avrodoc repository is currently built for and you are likely getting a javascript exception. See our pull request here that will resolve this issue: #2
> 
> This version not only adds additional functionality to the output from the avrodoc generator but also resolves the issue of the 'hang' you are referring to. Basically, in later versions of the avrotools utility, the root object in the AVSC file is re-structured and the current avrodoc code doesn't handle that.
> 
> Thanks,
> Micah
> Software Engineer :: Inome, Inc
> 
> —
> Reply to this email directly or view it on GitHub.

Mike Sherman
sherman94062@yahoo.com

**Comment by mphuff** [comment]
Mike--

You should be able to get latest code from master and your issue should be addressed.

Micah

**Comment by sherman94062** [comment]
Excellent, thanks!

**Comment by ept** [comment]
The new version is now released on npm, so you can just do `npm install avrodoc -g` to get it. Please let me know if you have any more problems.
